<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>AnyCPU;x64</Platforms>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <PublicizerRuntimeStrategies>Unsafe</PublicizerRuntimeStrategies>
    <RuntimeFrameworkVersion>9.0.1</RuntimeFrameworkVersion>
    <AssemblyName>CMod_Helper</AssemblyName>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.2.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Lib.Harmony" Version="2.3.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="Cosmoteer" IncludeCompilerGeneratedMembers="false" />
    <Publicize Include="HalflingCore" IncludeCompilerGeneratedMembers="false" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Cosmoteer">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Cosmoteer\Bin\Cosmoteer.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="HalflingCore">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Cosmoteer\Bin\HalflingCore.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

	<ItemGroup>
		<Compile Remove="C:\Users\aliser\.nuget\packages\krafs.publicizer\2.2.1\contentfiles\cs\any\Publicizer\IgnoresAccessChecksToAttribute.cs"></Compile>
		<Compile Remove="FileLogger - Copy.cs" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="powershell -File IntegrateAfterBuild.ps1 $(OutDir)" />
	</Target>
</Project>
